# ingress/cptm8-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cptm8-ingress
  namespace: cptm8-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
  - hosts:
    - app.cptm8.com
    - api.cptm8.com
    secretName: cptm8-tls
  rules:
  - host: app.cptm8.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashboardm8
            port:
              number: 3000
  - host: api.cptm8.com
    http:
      paths:
      - path: /asmm8
        pathType: Prefix
        backend:
          service:
            name: asmm8
            port:
              number: 8000